FROM prefecthq/prefect:2-python3.11

WORKDIR /app

COPY requirements-prod.txt .
RUN pip install --no-cache-dir -r requirements-prod.txt

COPY src/ ./src/
COPY pipeline/ ./pipeline/

ENV PREFECT_API_URL=""
ENV PREFECT_API_KEY=""
ENV PREFECT_WORKER_POOL="cloud-run-pool"

CMD ["python", "pipeline/prefect_agent.py"]
